import { createFileRoute } from "@tanstack/react-router";
import { Activity, Bluetooth, Brain, ShieldCheck, Waves } from "lucide-react";
import { PageHero } from "@/components/site/PageHero";
import hardwareImage from "@/assets/client/hardware/bwt-1.png";

export const Route = createFileRoute("/technology/bwt-2508")({
  head: () => ({ meta: [{ title: "BWT-2508 Neurofeedback Hardware | BrainWaves Tech" }] }),
  component: HardwarePage,
});
const highlights = [
  [Brain, "FP1 Prefrontal Cortex Alignment"],
  [Waves, "Dry Electrode Metallurgical Conductivity"],
  [Activity, "Ultra-Low Impedance Signal Grounding"],
  [Bluetooth, "Encrypted Bluetooth 5.2 Data Streaming"],
] as const;
const pipeline = [
  [
    "Micro-Voltage Capture",
    "Medical-grade dry electrodes contact the FP1 prefrontal skin surface, continuously picking up sub-microvolt raw brainwave signals ranging across 0.5 Hz to 42+ Hz.",
  ],
  [
    "Hardware Filtering",
    "Raw micro-volt signals pass through internal low-noise hardware filters that strip high-frequency environmental noise and power-line hum.",
  ],
  [
    "Automated Impedance & Grounding Verification",
    "Before transmission, the hardware checks electrical grounding against the user's skin and sends a fault code to software when fit thresholds are exceeded.",
  ],
  [
    "Encrypted Wireless Telemetry",
    "Cleaned, analog-to-digital EEG packets stream via Bluetooth 5.2 at ultra-low latency directly to the Windows host software engine.",
  ],
] as const;
const comparison = [
  ["Conductive Medium", "Requires messy saline gels/pastes", "100% Dry Sensor Metallurgy"],
  ["Preparation Time", "30 to 45 Minutes (Scalp Abrasion)", "1 to 2 Minutes Instant Setup"],
  ["Post-Scan Cleanup", "Hair washing & skin cleaning required", "Zero Cleanup; Instant Removal"],
  ["Sensor Contact", "19–32 Cap Electrodes", "3 Precision Prefrontal Electrodes"],
  [
    "Portability & Wear",
    "Bulky tethered wires & stationary cart",
    "Lightweight Wireless Bluetooth Headband",
  ],
] as const;
const specs = [
  ["Model Number", "BWT-2508"],
  ["Electrode Channels", "3 Active Sensors (Recording, Reference, Ground)"],
  ["Sensor Material", "Medical-Grade Dry Alloy Electrodes"],
  ["Frequency Range", "0.5 Hz to 42.0+ Hz (δ, θ, α, β, γ)"],
  ["Sampling Protocol", "High-resolution sub-Hertz telemetry"],
  ["Wireless Radius", "5 Meters via Bluetooth 5.2"],
  ["Battery System", "Lithium-Ion Dry Rechargeable Module (9 Hours Runtime)"],
  ["Safety Standards", "ISO 13485 · CE Certified · ISO 9001:2015 · RoHS Compliant"],
] as const;
function HardwarePage() {
  return (
    <>
      <PageHero
        eyebrow="BWT-2508"
        title="Neurofeedback Hardware Engineered for Zero-Noise Brainwave Telemetry"
        sub="Discover the electrical engineering, dry-sensor metallurgy, and micro-voltage signal conditioning that allow safe, real-time capture of brainwave spectrums from the prefrontal cortex."
      />
      <section className="bg-background py-16">
        <div className="mx-auto max-w-6xl px-4 lg:px-8">
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {highlights.map(([Icon, label]) => (
              <div key={label} className="rounded-2xl border border-navy/10 bg-white p-6">
                <Icon className="h-6 w-6 text-teal" />
                <p className="mt-4 font-display font-bold text-navy">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      <section className="bg-white py-16 lg:py-24">
        <div className="mx-auto grid max-w-6xl items-center gap-12 px-4 lg:grid-cols-2 lg:px-8">
          <img
            src={hardwareImage}
            alt="BWT-2508 neurofeedback headband"
            className="w-full rounded-3xl"
          />
          <div>
            <p className="text-xs font-bold uppercase tracking-[.18em] text-teal">
              Targeting the prefrontal cortex
            </p>
            <h2 className="mt-3 font-display text-3xl font-bold text-navy sm:text-4xl">
              Precision sensing at the FP1 axis.
            </h2>
            <p className="mt-5 leading-relaxed text-muted-foreground">
              The BWT-2508 captures electrical impulses generated by neurotransmission and
              neurostimulation from the prefrontal cortex—the FP1 position above the left-eye axis.
            </p>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              <b className="text-navy">Non-invasive micro-volt sensing.</b> Passive dry sensors are
              high-sensitivity receivers only: they never send electricity or current into the
              brain.
            </p>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              <b className="text-navy">Dual reference & ground pin architecture.</b> Integrated
              reference and ground electrodes establish an immediate electrical baseline, reducing
              static and muscle-movement artefacts.
            </p>
          </div>
        </div>
      </section>
      <section className="bg-background py-16 lg:py-24">
        <div className="mx-auto max-w-6xl px-4 lg:px-8">
          <p className="text-xs font-bold uppercase tracking-[.18em] text-teal">
            Gel-free neuro-mapping
          </p>
          <h2 className="mt-3 font-display text-3xl font-bold text-navy sm:text-4xl">
            The metallurgy of effortless setup.
          </h2>
          <div className="mt-9 overflow-x-auto rounded-2xl border border-navy/10 bg-white">
            <table className="w-full min-w-[680px] text-left text-sm">
              <thead className="bg-navy text-white">
                <tr>
                  <th className="p-4">Technical Feature</th>
                  <th className="p-4">Traditional Clinical Wet EEG</th>
                  <th className="p-4">BWT-2508 Dry Electrode Tech</th>
                </tr>
              </thead>
              <tbody>
                {comparison.map((row) => (
                  <tr key={row[0]} className="border-t border-navy/10">
                    <th className="p-4 font-semibold text-navy">{row[0]}</th>
                    <td className="p-4 text-muted-foreground">{row[1]}</td>
                    <td className="p-4 font-medium text-teal">{row[2]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>
      <section className="bg-navy py-16 text-white lg:py-24">
        <div className="mx-auto max-w-6xl px-4 lg:px-8">
          <p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Signal pipeline</p>
          <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
            Hardware telemetry, from signal to software.
          </h2>
          <div className="mt-10 grid gap-5 md:grid-cols-2">
            {pipeline.map(([title, text], i) => (
              <article key={title} className="rounded-2xl border border-white/15 bg-white/5 p-6">
                <span className="text-sm font-bold text-teal">STAGE {i + 1}</span>
                <h3 className="mt-3 font-display text-xl font-bold">{title}</h3>
                <p className="mt-3 leading-relaxed text-white/70">{text}</p>
              </article>
            ))}
          </div>
        </div>
      </section>
      <section className="bg-white py-16 lg:py-24">
        <div className="mx-auto max-w-4xl px-4 lg:px-8">
          <p className="text-center text-xs font-bold uppercase tracking-[.18em] text-teal">
            Technical dataset
          </p>
          <h2 className="mt-3 text-center font-display text-3xl font-bold text-navy sm:text-4xl">
            BWT-2508 specifications
          </h2>
          <dl className="mt-10 divide-y divide-navy/10 rounded-2xl border border-navy/10">
            {specs.map(([term, detail]) => (
              <div key={term} className="grid gap-1 p-5 sm:grid-cols-[13rem_1fr]">
                <dt className="font-semibold text-navy">{term}</dt>
                <dd className="text-muted-foreground">{detail}</dd>
              </div>
            ))}
          </dl>
        </div>
      </section>
    </>
  );
}
