/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PractitionerRouteImport } from './routes/practitioner'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as SolutionsRehabRouteImport } from './routes/solutions.rehab'
import { Route as SolutionsPsychologistsRouteImport } from './routes/solutions.psychologists'
import { Route as SolutionsHealthcareRouteImport } from './routes/solutions.healthcare'
import { Route as SolutionsEducationalRouteImport } from './routes/solutions.educational'
import { Route as SolutionsCorporatesRouteImport } from './routes/solutions.corporates'
import { Route as ProductsSoundTherapyRouteImport } from './routes/products.sound-therapy'
import { Route as ProductsSoftwareRouteImport } from './routes/products.software'
import { Route as ProductsHeadbandRouteImport } from './routes/products.headband'
import { Route as ProductsAccessoriesRouteImport } from './routes/products.accessories'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicEnquiriesRouteImport } from './routes/api/public/enquiries'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin/people'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin/enquiries'
import { Route as AuthenticatedAdminCaseStudiesRouteImport } from './routes/_authenticated/admin/case-studies'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin/blog/index'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin/blog/$id'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerRoute = PractitionerRouteImport.update({
  id: '/practitioner',
  path: '/practitioner',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRehabRoute = SolutionsRehabRouteImport.update({
  id: '/solutions/rehab',
  path: '/solutions/rehab',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPsychologistsRoute = SolutionsPsychologistsRouteImport.update({
  id: '/solutions/psychologists',
  path: '/solutions/psychologists',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHealthcareRoute = SolutionsHealthcareRouteImport.update({
  id: '/solutions/healthcare',
  path: '/solutions/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsEducationalRoute = SolutionsEducationalRouteImport.update({
  id: '/solutions/educational',
  path: '/solutions/educational',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCorporatesRoute = SolutionsCorporatesRouteImport.update({
  id: '/solutions/corporates',
  path: '/solutions/corporates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSoundTherapyRoute = ProductsSoundTherapyRouteImport.update({
  id: '/products/sound-therapy',
  path: '/products/sound-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSoftwareRoute = ProductsSoftwareRouteImport.update({
  id: '/products/software',
  path: '/products/software',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHeadbandRoute = ProductsHeadbandRouteImport.update({
  id: '/products/headband',
  path: '/products/headband',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAccessoriesRoute = ProductsAccessoriesRouteImport.update({
  id: '/products/accessories',
  path: '/products/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicEnquiriesRoute = ApiPublicEnquiriesRouteImport.update({
  id: '/api/public/enquiries',
  path: '/api/public/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/admin/testimonials',
    path: '/admin/testimonials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/admin/people',
    path: '/admin/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/admin/enquiries',
    path: '/admin/enquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCaseStudiesRoute =
  AuthenticatedAdminCaseStudiesRouteImport.update({
    id: '/admin/case-studies',
    path: '/admin/case-studies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/admin/blog/',
    path: '/admin/blog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/admin/blog/$id',
    path: '/admin/blog/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/practitioner': typeof PractitionerRoute
  '/research': typeof ResearchRoute
  '/stories': typeof StoriesRoute
  '/technology': typeof TechnologyRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/headband': typeof ProductsHeadbandRoute
  '/products/software': typeof ProductsSoftwareRoute
  '/products/sound-therapy': typeof ProductsSoundTherapyRoute
  '/solutions/corporates': typeof SolutionsCorporatesRoute
  '/solutions/educational': typeof SolutionsEducationalRoute
  '/solutions/healthcare': typeof SolutionsHealthcareRoute
  '/solutions/psychologists': typeof SolutionsPsychologistsRoute
  '/solutions/rehab': typeof SolutionsRehabRoute
  '/products/': typeof ProductsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/practitioner': typeof PractitionerRoute
  '/research': typeof ResearchRoute
  '/stories': typeof StoriesRoute
  '/technology': typeof TechnologyRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/headband': typeof ProductsHeadbandRoute
  '/products/software': typeof ProductsSoftwareRoute
  '/products/sound-therapy': typeof ProductsSoundTherapyRoute
  '/solutions/corporates': typeof SolutionsCorporatesRoute
  '/solutions/educational': typeof SolutionsEducationalRoute
  '/solutions/healthcare': typeof SolutionsHealthcareRoute
  '/solutions/psychologists': typeof SolutionsPsychologistsRoute
  '/solutions/rehab': typeof SolutionsRehabRoute
  '/products': typeof ProductsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/practitioner': typeof PractitionerRoute
  '/research': typeof ResearchRoute
  '/stories': typeof StoriesRoute
  '/technology': typeof TechnologyRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/headband': typeof ProductsHeadbandRoute
  '/products/software': typeof ProductsSoftwareRoute
  '/products/sound-therapy': typeof ProductsSoundTherapyRoute
  '/solutions/corporates': typeof SolutionsCorporatesRoute
  '/solutions/educational': typeof SolutionsEducationalRoute
  '/solutions/healthcare': typeof SolutionsHealthcareRoute
  '/solutions/psychologists': typeof SolutionsPsychologistsRoute
  '/solutions/rehab': typeof SolutionsRehabRoute
  '/products/': typeof ProductsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/_authenticated/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/practitioner'
    | '/research'
    | '/stories'
    | '/technology'
    | '/testimonials'
    | '/blog/$slug'
    | '/products/accessories'
    | '/products/headband'
    | '/products/software'
    | '/products/sound-therapy'
    | '/solutions/corporates'
    | '/solutions/educational'
    | '/solutions/healthcare'
    | '/solutions/psychologists'
    | '/solutions/rehab'
    | '/products/'
    | '/solutions/'
    | '/admin/case-studies'
    | '/admin/enquiries'
    | '/admin/media'
    | '/admin/people'
    | '/admin/testimonials'
    | '/api/public/bootstrap-admin'
    | '/api/public/enquiries'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/practitioner'
    | '/research'
    | '/stories'
    | '/technology'
    | '/testimonials'
    | '/blog/$slug'
    | '/products/accessories'
    | '/products/headband'
    | '/products/software'
    | '/products/sound-therapy'
    | '/solutions/corporates'
    | '/solutions/educational'
    | '/solutions/healthcare'
    | '/solutions/psychologists'
    | '/solutions/rehab'
    | '/products'
    | '/solutions'
    | '/admin/case-studies'
    | '/admin/enquiries'
    | '/admin/media'
    | '/admin/people'
    | '/admin/testimonials'
    | '/api/public/bootstrap-admin'
    | '/api/public/enquiries'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/practitioner'
    | '/research'
    | '/stories'
    | '/technology'
    | '/testimonials'
    | '/blog/$slug'
    | '/products/accessories'
    | '/products/headband'
    | '/products/software'
    | '/products/sound-therapy'
    | '/solutions/corporates'
    | '/solutions/educational'
    | '/solutions/healthcare'
    | '/solutions/psychologists'
    | '/solutions/rehab'
    | '/products/'
    | '/solutions/'
    | '/_authenticated/admin/case-studies'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/testimonials'
    | '/api/public/bootstrap-admin'
    | '/api/public/enquiries'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PractitionerRoute: typeof PractitionerRoute
  ResearchRoute: typeof ResearchRoute
  StoriesRoute: typeof StoriesRoute
  TechnologyRoute: typeof TechnologyRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ProductsAccessoriesRoute: typeof ProductsAccessoriesRoute
  ProductsHeadbandRoute: typeof ProductsHeadbandRoute
  ProductsSoftwareRoute: typeof ProductsSoftwareRoute
  ProductsSoundTherapyRoute: typeof ProductsSoundTherapyRoute
  SolutionsCorporatesRoute: typeof SolutionsCorporatesRoute
  SolutionsEducationalRoute: typeof SolutionsEducationalRoute
  SolutionsHealthcareRoute: typeof SolutionsHealthcareRoute
  SolutionsPsychologistsRoute: typeof SolutionsPsychologistsRoute
  SolutionsRehabRoute: typeof SolutionsRehabRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicEnquiriesRoute: typeof ApiPublicEnquiriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner': {
      id: '/practitioner'
      path: '/practitioner'
      fullPath: '/practitioner'
      preLoaderRoute: typeof PractitionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/rehab': {
      id: '/solutions/rehab'
      path: '/solutions/rehab'
      fullPath: '/solutions/rehab'
      preLoaderRoute: typeof SolutionsRehabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/psychologists': {
      id: '/solutions/psychologists'
      path: '/solutions/psychologists'
      fullPath: '/solutions/psychologists'
      preLoaderRoute: typeof SolutionsPsychologistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/healthcare': {
      id: '/solutions/healthcare'
      path: '/solutions/healthcare'
      fullPath: '/solutions/healthcare'
      preLoaderRoute: typeof SolutionsHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/educational': {
      id: '/solutions/educational'
      path: '/solutions/educational'
      fullPath: '/solutions/educational'
      preLoaderRoute: typeof SolutionsEducationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/corporates': {
      id: '/solutions/corporates'
      path: '/solutions/corporates'
      fullPath: '/solutions/corporates'
      preLoaderRoute: typeof SolutionsCorporatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/sound-therapy': {
      id: '/products/sound-therapy'
      path: '/products/sound-therapy'
      fullPath: '/products/sound-therapy'
      preLoaderRoute: typeof ProductsSoundTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/software': {
      id: '/products/software'
      path: '/products/software'
      fullPath: '/products/software'
      preLoaderRoute: typeof ProductsSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/headband': {
      id: '/products/headband'
      path: '/products/headband'
      fullPath: '/products/headband'
      preLoaderRoute: typeof ProductsHeadbandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/accessories': {
      id: '/products/accessories'
      path: '/products/accessories'
      fullPath: '/products/accessories'
      preLoaderRoute: typeof ProductsAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/enquiries': {
      id: '/api/public/enquiries'
      path: '/api/public/enquiries'
      fullPath: '/api/public/enquiries'
      preLoaderRoute: typeof ApiPublicEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/case-studies': {
      id: '/_authenticated/admin/case-studies'
      path: '/admin/case-studies'
      fullPath: '/admin/case-studies'
      preLoaderRoute: typeof AuthenticatedAdminCaseStudiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCaseStudiesRoute: typeof AuthenticatedAdminCaseStudiesRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCaseStudiesRoute: AuthenticatedAdminCaseStudiesRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PractitionerRoute: PractitionerRoute,
  ResearchRoute: ResearchRoute,
  StoriesRoute: StoriesRoute,
  TechnologyRoute: TechnologyRoute,
  TestimonialsRoute: TestimonialsRoute,
  ProductsAccessoriesRoute: ProductsAccessoriesRoute,
  ProductsHeadbandRoute: ProductsHeadbandRoute,
  ProductsSoftwareRoute: ProductsSoftwareRoute,
  ProductsSoundTherapyRoute: ProductsSoundTherapyRoute,
  SolutionsCorporatesRoute: SolutionsCorporatesRoute,
  SolutionsEducationalRoute: SolutionsEducationalRoute,
  SolutionsHealthcareRoute: SolutionsHealthcareRoute,
  SolutionsPsychologistsRoute: SolutionsPsychologistsRoute,
  SolutionsRehabRoute: SolutionsRehabRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicEnquiriesRoute: ApiPublicEnquiriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
